package com.guru.oplmanager.ui.theme

import androidx.compose.ui.graphics.Color

val Primary = Color(0xFF6366F1)
val OnPrimary = Color(0xFFFFFFFF)
val PrimaryContainer = Color(0xFFE0E7FF)
val OnPrimaryContainer = Color(0xFF1E1B4B)
val Secondary = Color(0xFF7C3AED)
val OnSecondary = Color(0xFFFFFFFF)
val SecondaryContainer = Color(0xFFEDE9FE)
val OnSecondaryContainer = Color(0xFF2E1065)
val Tertiary = Color(0xFF0891B2)
val OnTertiary = Color(0xFFFFFFFF)
val TertiaryContainer = Color(0xFFCFFAFE)
val OnTertiaryContainer = Color(0xFF001F23)
val Error = Color(0xFFDC2626)
val OnError = Color(0xFFFFFFFF)
val ErrorContainer = Color(0xFFFEE2E2)
val OnErrorContainer = Color(0xFF7F1D1D)
val Background = Color(0xFFFAFAFA)
val OnBackground = Color(0xFF1F2937)
val Surface = Color(0xFFFFFFFF)
val OnSurface = Color(0xFF1F2937)

val PrimaryDark = Color(0xFFC7D2FE)
val OnPrimaryDark = Color(0xFF312E81)
val PrimaryContainerDark = Color(0xFF4F46E5)
val OnPrimaryContainerDark = Color(0xFFE0E7FF)
val SecondaryDark = Color(0xFFDDD6FE)
val OnSecondaryDark = Color(0xFF4C1D95)
val SecondaryContainerDark = Color(0xFF7C3AED)
val OnSecondaryContainerDark = Color(0xFFEDE9FE)
val TertiaryDark = Color(0xFFA5F3FC)
val OnTertiaryDark = Color(0xFF003F47)
val TertiaryContainerDark = Color(0xFF006B76)
val OnTertiaryContainerDark = Color(0xFFCFFAFE)
val ErrorDark = Color(0xFFFCA5A5)
val OnErrorDark = Color(0xFF5F0F0F)
val ErrorContainerDark = Color(0xFF842029)
val OnErrorContainerDark = Color(0xFFFEE2E2)
val BackgroundDark = Color(0xFF0F172A)
val OnBackgroundDark = Color(0xFFEBF8FF)
val SurfaceDark = Color(0xFF0F172A)
val OnSurfaceDark = Color(0xFFEBF8FF)
